### ISSUE TITLE
Crystalbuntu running on AppleTV (1st Gen) XBMC crashes on start

### ISSUE THREAD

**Issue by agzela** [akezeke/spotyxbmc2#14]
###### ########## SYSTEM INFO

 Date: Sun Dec 11 04:05:54 GMT 2011
 XBMC Options: 
 Arch: i686
 Kernel: Linux 2.6.24-28-generic #1 SMP Sat Oct 16 17:46:03 UTC 2010
 Release: 
    Distributor ID: Ubuntu
    Description:    Ubuntu 8.04.4 LTS
    Release:    8.04
    Codename:   hardy
###### ######### STACK TRACE

=====>  Core file: /home/atv/scripts/core.4564 (2011-12-11 04:05:54.000000000 +0000)
        =========================================
Core was generated by `/usr/local/lib/xbmc/xbmc.bin --standalone'.
Program terminated with signal 11, Segmentation fault.
[New process 4602]
[New process 4597]
[New process 4596]
[New process 4595]
[New process 4592]
[New process 4591]
[New process 4590]
[New process 4589]
[New process 4588]
[New process 4587]
[New process 4586]
[New process 4564]
#0  addon_music_spotify::StarredBackgroundLoader::Process (this=0xb32ba258)

```
at spotyXBMC/playlist/StarredBackgroundLoader.cpp:54
in spotyXBMC/playlist/StarredBackgroundLoader.cpp
```

Thread 12 (process 4564):
#0  0x08c2eb93 in CApplication::Render (this=0x91b0fe0) at Application.cpp:1962
#1  0x08d01f2e in CXBApplicationEx::Run (this=0x91b0fe0)

```
at XBApplicationEx.cpp:146
```
#2  0x08d0862a in main (argc=2, argv=0xbfd3b8a4) at xbmc.cpp:93

Thread 11 (process 4586):
#0  0xb76e7410 in __kernel_vsyscall ()
#1  0xb691d196 in nanosleep () from /lib/tls/i686/cmov/libpthread.so.0
#2  0x0826981c in Sleep (dwMilliSeconds=2990965272) at XTimeUtils.cpp:63
#3  0x08bdb819 in CThread::Sleep (this=0x9a65dd8, milliseconds=5)

```
at Thread.cpp:532
```
#4  0x08b01549 in addon_music_spotify::BackgroundThread::Process (

```
this=0x9a65dd8) at spotyXBMC/session/BackgroundThread.cpp:59
```
#5  0x08bdbb65 in CThread::staticThread (data=0x9a65dd8) at Thread.cpp:177
#6  0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#7  0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 10 (process 4587):
#0  0xb76e7410 in __kernel_vsyscall ()
#1  0xb691bd05 in sem_wait@@GLIBC_2.1 ()

   from /lib/tls/i686/cmov/libpthread.so.0
#2  0xb750a7cf in ?? () from /usr/lib/libspotify.so.10
#3  0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#4  0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 9 (process 4588):
#0  0xb76e7410 in __kernel_vsyscall ()
#1  0xb6010cc7 in poll () from /lib/tls/i686/cmov/libc.so.6
#2  0xb759d6a3 in ?? () from /usr/lib/libspotify.so.10
#3  0xb759dba1 in ?? () from /usr/lib/libspotify.so.10
#4  0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#5  0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 8 (process 4589):
#0  0xb76e7410 in __kernel_vsyscall ()
#1  0xb691cbb8 in accept () from /lib/tls/i686/cmov/libpthread.so.0
#2  0xb337a4ff in sock_accept (s=0xb323cbb0)

```
at /home/user/Python-2.6.7/Modules/socketmodule.c:1622
```
#3  0x08ddf60a in PyEval_EvalFrameEx (f=0x9ec4054, throwflag=0)

```
at Python/ceval.c:3734
```
#4  0x08ddf9bc in PyEval_EvalFrameEx (f=0x9ec71f4, throwflag=0)

```
at Python/ceval.c:3836
```
#5  0x08ddf9bc in PyEval_EvalFrameEx (f=0x9ef2884, throwflag=0)

```
at Python/ceval.c:3836
```
#6  0x08ddf9bc in PyEval_EvalFrameEx (f=0x9dc508c, throwflag=0)

```
at Python/ceval.c:3836
```
#7  0x08de12c0 in PyEval_EvalCodeEx (co=0x9d3b3c8, globals=0x9d370b4,

```
locals=0x9d370b4, args=0x0, argcount=0, kws=0x0, kwcount=0, defs=0x0, 
defcount=0, closure=0x0) at Python/ceval.c:3000
```
#8  0x08de1407 in PyEval_EvalCode (co=0x9d3b3c8, globals=0x9d370b4,

```
locals=0x9d370b4) at Python/ceval.c:541
```
#9  0x08e01e9c in PyRun_FileExFlags (fp=0x9d946b8,

```
filename=0x9c40ccc "/root/.xbmc/addons/script.common.plugin.cache/default.py", start=257, globals=0x9d370b4, locals=0x9d370b4, closeit=1, flags=0x0)
at Python/pythonrun.c:1351
```
#10 0x089efad4 in XBPyThread::Process (this=0x9d0f1d8) at XBPyThread.cpp:256
#11 0x08bdbb65 in CThread::staticThread (data=0x9d0f1d8) at Thread.cpp:177
#12 0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#13 0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 7 (process 4590):
#0  0xb76e7410 in __kernel_vsyscall ()
#1  0xb6919dd2 in pthread_cond_timedwait@@GLIBC_2.3.2 ()

   from /lib/tls/i686/cmov/libpthread.so.0
#2  0x08319ef4 in CJobManager::GetNextJob (this=0x919b660, worker=0x9d8d508)

```
at /builddir/akezeke-spotyxbmc2-d362cfa/xbmc/threads/platform/pthreads/Condition.h:74
```
#3  0x0831a033 in CJobWorker::Process (this=0x9d8d508) at JobManager.cpp:57
#4  0x08bdbb65 in CThread::staticThread (data=0x9d8d508) at Thread.cpp:177
#5  0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#6  0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 6 (process 4591):
#0  0xb76e7410 in __kernel_vsyscall ()
#1  0xb6919dd2 in pthread_cond_timedwait@@GLIBC_2.3.2 ()

   from /lib/tls/i686/cmov/libpthread.so.0
#2  0x08319ef4 in CJobManager::GetNextJob (this=0x919b660, worker=0x9e808e0)

```
at /builddir/akezeke-spotyxbmc2-d362cfa/xbmc/threads/platform/pthreads/Condition.h:74
```
#3  0x0831a033 in CJobWorker::Process (this=0x9e808e0) at JobManager.cpp:57
#4  0x08bdbb65 in CThread::staticThread (data=0x9e808e0) at Thread.cpp:177
#5  0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#6  0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 5 (process 4592):
#0  0xb5fb7a5c in memcpy () from /lib/tls/i686/cmov/libc.so.6
#1  0x08912b12 in SZipEntry (this=0x9324a40, SNewItem=@0xa02fcb8)

```
at ZipManager.h:94
```
#2  0x08912cce in std::vector<SZipEntry, std::allocator<SZipEntry> >::operator=

```
(this=0xb0463de4, __x=@0x9cfa87c)
at /usr/include/c++/4.2/bits/stl_construct.h:81
```
#3  0x0891289c in CZipManager::GetZipEntry (this=0x91abcc0,

```
strPath=@0xb0463ec0, item=@0xa013d08) at ZipManager.cpp:228
```
#4  0x08877957 in XFILE::CFileZip::Open (this=0xa013cf0, url=@0xb0463f20)

```
at FileZip.cpp:54
```
#5  0x088598c0 in XFILE::CFile::Open (this=0xb0464090,

```
strFileName=@0xb04640e4, flags=<value optimized out>) at File.cpp:242
```
#6  0x0885a048 in XFILE::CFile::Cache (strFileName=@0xb046418c,

```
strDest=@0xb0464188, pCallback=0x0, pContext=0x0) at File.cpp:87
```
#7  0x08911f69 in CZipManager::ExtractArchive (this=0x91abcc0,

```
strArchive=@0xb0464278, strPath=@0xb0464274) at ZipManager.cpp:257
```
#8  0x083900bd in CWeatherJob::DoWork (this=0x9e495e8) at Weather.cpp:106
#9  0x0831a008 in CJobWorker::Process (this=0x9db9510) at JobManager.cpp:62
#10 0x08bdbb65 in CThread::staticThread (data=0x9db9510) at Thread.cpp:177
#11 0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#12 0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 4 (process 4595):
#0  0xb76e7410 in __kernel_vsyscall ()
#1  0xb6013941 in select () from /lib/tls/i686/cmov/libc.so.6
#2  0x08287699 in SOCKETS::CSocketListener::Listen (this=0xaec61190, timeout=0)

```
at Socket.cpp:195
```
#3  0x0827cf6c in EVENTSERVER::CEventServer::Run (this=0x9e76458)

```
at EventServer.cpp:209
```
#4  0x0827d356 in EVENTSERVER::CEventServer::Process (this=0x9e76458)

```
at EventServer.cpp:147
```
#5  0x08bdbb65 in CThread::staticThread (data=0x9e76458) at Thread.cpp:177
#6  0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#7  0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 3 (process 4596):
#0  0xb76e7410 in __kernel_vsyscall ()
#1  0xb6013941 in select () from /lib/tls/i686/cmov/libc.so.6
#2  0x08289af9 in JSONRPC::CTCPServer::Process (this=0x9e783e0)

```
at TCPServer.cpp:120
```
#3  0x08bdbb65 in CThread::staticThread (data=0x9e783e8) at Thread.cpp:177
#4  0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#5  0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 2 (process 4597):
#0  0xb76e7410 in __kernel_vsyscall ()
#1  0xb6010cc7 in poll () from /lib/tls/i686/cmov/libc.so.6
#2  0xb6dd9e6e in ?? () from /usr/lib/libavahi-common.so.3
#3  0xb6dd87ea in avahi_simple_poll_run () from /usr/lib/libavahi-common.so.3
#4  0xb6dd915f in avahi_simple_poll_iterate ()

   from /usr/lib/libavahi-common.so.3
#5  0xb6dd91b0 in avahi_simple_poll_loop () from /usr/lib/libavahi-common.so.3
#6  0xb6dd9d1b in ?? () from /usr/lib/libavahi-common.so.3
#7  0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#8  0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 1 (process 4602):
#0  addon_music_spotify::StarredBackgroundLoader::Process (this=0xb32ba258)

```
at spotyXBMC/playlist/StarredBackgroundLoader.cpp:54
```
#1  0x08bdbb65 in CThread::staticThread (data=0xb32ba258) at Thread.cpp:177
#2  0xb69154fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#3  0xb601af5e in clone () from /lib/tls/i686/cmov/libc.so.6

**Comment by agzela** [comment]
Fresh Crystalbuntu install.....spotyxbmc2 build crashes after setting credentials after a restart.
